### ISSUE TITLE
black and white areas of the spectrum have a hard drop off (different from visual representation)

### ISSUE THREAD

**Issue by piemonte** [gizmosachin/ColorSlider#21]
would it be possible to match the visuals themselves?
![pasted_image_at_2017_10_06_08_54_pm_720](https://user-images.githubusercontent.com/1870667/31303284-af81c8bc-aabf-11e7-81fb-d8eeb175a4be.png)

**Comment by gizmosachin** [comment]
Oops, that's really bad and completely unintentional. Will push a fix.

**Comment by piemonte** [comment]
(sorry, my screenshot represents the behavior not the actual visuals)

**Comment by gizmosachin** [comment]
Ah okay, no worries! 

Based on the way the colors are drawn in the `GradientView` there'll always be a hard drop off unfortunately (Snapchat's new color picker actually does this as well). I noticed it's particularly bad when you have a longer slider though, so I'll see if I can come up with a fix and push that. If it'd be more preferable to just hide the black and white colors altogether instead (the old behavior), you can also set the insets for black and white to zero:
```swift
let gradientView = colorSlider.gradientView
gradientView.blackInset = 0
gradientView.whiteInset = 0
```

**Comment by gizmosachin** [comment]
Forget what I said earlier - `GradientView` now draws the gradient so it's continuous, even with the black and white at the ends. `pod update` to v4.1 should do the trick. 😄

**Comment by piemonte** [comment]
🙌
