### ISSUE TITLE
QUESTION: Switching starter color (black to white instead of white to black)

### ISSUE THREAD

**Issue by roimulia** [gizmosachin/ColorSlider#23]
Hey! Thank you for this awesome library. 

One small question. If I need to change the starter color (from white to black, to black to right, in my case), how would you recommend doing that?

**Comment by gizmosachin** [comment]
Hi @roimulia! Sorry for the late response. Unfortunately this isn't supported at the moment. 

I'd recommend forking the project and modifying [GradientView.swift](https://github.com/gizmosachin/ColorSlider/blob/master/Sources/GradientView.swift) if changing the starter color is essential. 

Alternatively, you could try using a `CGAffineTransformScale` with a `x` or `y` equal to `-1` (depending on the orientation) to flip the ColorSlider on its axis.
