### ISSUE TITLE
Manually setting randomly calculated color

### ISSUE THREAD

**Issue by sabiland** [gizmosachin/ColorSlider#27]
If you manually set randomly calculated color, ColorSlider (though setting correct color) slider's position is not set appropriately (always at the 0 position on the left).
I understand why (because ColorsSlider does not "contain" every color possible), but it would be cool if control could approx. calculate the correct position.

**Comment by gizmosachin** [comment]
Thanks @sabiland! I noticed this recently as well. Just pushed a change to enable this - updating to version`4.2` should do the trick.

**Comment by Mohsenkhodadadzadeh** [comment]
I want to change point place on slider programmatically, how can I do it
I saw your committee changes and I just guess I should do it with these lines :
```
colorSlider.color = newColor
colorSlider. layoutSubviews()
```
but it's wrong , could you give me the way , please
