### ISSUE TITLE
Can't use in Interface Builder

### ISSUE THREAD

**Issue by AndrewSB** [gizmosachin/ColorSlider#6]
Thanks for all the work @gizmosachin! Great project.

I've been trying to integrate the component like you did in Sketchpad, but for some reason IB is refusing to recognize ColorSlider as a valid subclass for a UIView...

Have you had any experience with this/ know how to debug this?

**Comment by gizmosachin** [comment]
Hey @AndrewSB, thanks for the kind words. I tried integrating ColorSlider by dragging the file in from Finder + integrating it in IB and it succeeded. If you're using some variation of the framework build (including CocoaPods / Carthage) can you check that the module name in IB is set to ColorSlider?

**Comment by AndrewSB** [comment]
Resolved the issue, turns out when you use a `framework` (like through Carthage for instance), you lose all the `@IBDesignable` and `@IBInspectable` attributes.

You also lose class and module name completion in IB. Believe there's already a radar open with apple.

**Comment by gizmosachin** [comment]
Oh, interesting – I wasn't aware of that. Thanks for the update!
